import XCTest
import PDFKit
import AppKit
@testable import PaperShelfCore
@testable import PaperShelf

@MainActor
final class NoteSidecarTests: XCTestCase {

    func testAnnotationsWriteAndOverwriteTheSiblingSidecar() async throws {
        let folder = FileManager.default.temporaryDirectory
            .appendingPathComponent("sidecar-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: folder) }

        let pdf = folder.appendingPathComponent("paper.pdf")
        try makeTextPDF(at: pdf, text: "alpha")
        let view = PDFView()
        view.document = try XCTUnwrap(PDFDocument(url: pdf))
        let annotator = Annotator()
        let prefs = Prefs.shared
        let oldSync = prefs.syncNotesSidecar
        defer { prefs.syncNotesSidecar = oldSync }
        prefs.syncNotesSidecar = true
        annotator.attach(view, url: pdf)
        let style = Palette.shared.styles[0]
        let scope = HighlightMeaningScope.forDocument(pdf, id: "sidecar-document")
        defer { Palette.shared.resetMeanings(in: scope) }
        Palette.shared.setMeaning("Delete", on: style, scope: scope)
        annotator.setDocumentID("sidecar-document")
        view.currentSelection = try XCTUnwrap(view.document?.findString("alpha", withOptions: []).first)

        XCTAssertEqual(annotator.highlightSelection(colour: style.nsColor, note: "keep"), 1)
        annotator.flush()
        let sidecar = notesSidecarURL(for: pdf)
        let first = try await waitForText(at: sidecar, containing: "keep")
        XCTAssertTrue(first.contains("Generated by PaperShelf"))
        XCTAssertTrue(first.contains("Colour: `#"))
        XCTAssertTrue(first.contains("*Delete*"), first)

        let mark = try XCTUnwrap(annotator.marks.first)
        prefs.syncNotesSidecar = false
        annotator.setNote("do not rewrite", on: mark)
        annotator.flush()
        try await Task.sleep(for: .milliseconds(100))
        XCTAssertEqual(try String(contentsOf: sidecar), first)
    }

    func testACompletedRenameMovesTheExistingSidecar() throws {
        let folder = FileManager.default.temporaryDirectory
            .appendingPathComponent("sidecar-move-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: folder) }

        let oldPDF = folder.appendingPathComponent("old.pdf")
        let newPDF = folder.appendingPathComponent("new.pdf")
        let oldSidecar = notesSidecarURL(for: oldPDF)
        try Data("managed".utf8).write(to: oldSidecar)
        let item = PaperShelfCore.Item(root: folder, source: oldPDF, destination: newPDF,
                                       status: .renamed, carriedOut: true)

        moveNotesSidecar(for: item)

        XCTAssertFalse(FileManager.default.fileExists(atPath: oldSidecar.path))
        XCTAssertEqual(try String(contentsOf: notesSidecarURL(for: newPDF)), "managed")
    }

    private func waitForText(at url: URL, containing needle: String) async throws -> String {
        for _ in 0..<50 {
            if let text = try? String(contentsOf: url), text.contains(needle) { return text }
            try await Task.sleep(for: .milliseconds(20))
        }
        return try String(contentsOf: url)
    }
}
