import Foundation
import PDFKit

/// One highlight or note, flattened for export.
public struct MarkExport: Sendable, Equatable {
    public let page: Int
    public let quoted: String
    public let note: String
    /// When the PDF annotation was last changed.
    public let timestamp: Date
    /// What the colour it was made with stands for, if the palette names it.
    public let meaning: String
    /// The stored colour, kept so a sidecar can be understood without the app's palette.
    public let colour: String

    public init(page: Int, quoted: String, note: String, meaning: String,
                colour: String = "", timestamp: Date = Date()) {
        self.page = page
        self.quoted = quoted
        self.note = note
        self.meaning = meaning
        self.colour = colour
        self.timestamp = timestamp
    }
}

/// The managed Markdown file beside a PDF, kept distinct from a hand-authored `.md` with
/// the same stem.
public func notesSidecarURL(for pdf: URL) -> URL {
    let stem = pdf.deletingPathExtension().lastPathComponent
    return pdf.deletingLastPathComponent().appendingPathComponent(stem + " notes.md")
}

/// Escapes only what would otherwise be read as structure.
///
/// Not every special character: a quotation full of backslashes is harder to read than
/// one where an asterisk happened to render as emphasis. What matters is that a line
/// cannot turn itself into a heading, a list item, a quote or a table cell.
public func markdownEscape(_ text: String, inTable: Bool = false) -> String {
    var out = text.replacingOccurrences(of: "\\", with: "\\\\")
    if inTable {
        out = out.replacingOccurrences(of: "|", with: "\\|")
        out = out.replacingOccurrences(of: "\n", with: " ")
    }
    // Only at the start of a line, where these mean something.
    let leading = ["#", ">", "-", "+", "*"]
    if let first = out.first.map(String.init), leading.contains(first) {
        out = "\\" + out
    }
    return out
}

/// A document's marks as reading notes: what was highlighted, what was written about it,
/// and where to find it again.
public func markdownNotes(title: String, source: String, marks: [MarkExport],
                          date: Date = Date()) -> String {
    var out = "<!-- Generated by PaperShelf. Do not edit; this file is overwritten from PDF annotations. -->\n\n"
    out += "# \(markdownEscape(title))\n\n"
    out += "`\(source)`\n\n"
    if marks.isEmpty {
        out += "_No highlights or notes._\n"
        return out
    }

    let stamp = DateFormatter()
    stamp.locale = Locale(identifier: "en_US_POSIX")
    stamp.dateFormat = "yyyy-MM-dd"
    out += "\(marks.count) mark\(marks.count == 1 ? "" : "s"), exported \(stamp.string(from: date))\n\n"

    var page = -1
    let markStamp = ISO8601DateFormatter()
    markStamp.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
    for mark in marks.sorted(by: { $0.page < $1.page }) {
        if mark.page != page {
            page = mark.page
            out += "## Page \(page)\n\n"
        }
        if !mark.quoted.isEmpty {
            // A quotation is a quotation, so it goes in a blockquote.
            out += "> \(markdownEscape(mark.quoted))\n\n"
        }
        if !mark.note.isEmpty {
            out += "\(markdownEscape(mark.note))\n\n"
        }
        out += "Marked \(markStamp.string(from: mark.timestamp))\n\n"
        if !mark.colour.isEmpty {
            out += "Colour: `\(mark.colour)`\n\n"
        }
        if !mark.meaning.isEmpty && mark.meaning != "Highlight" {
            out += "*\(markdownEscape(mark.meaning))*\n\n"
        }
    }
    return out
}

/// The collection as a table: what each file will be called, and what is known about it.
public func markdownCatalogue(_ items: [Item], known: [String: BookGuess] = [:],
                              date: Date = Date()) -> String {
    let stamp = DateFormatter()
    stamp.locale = Locale(identifier: "en_US_POSIX")
    stamp.dateFormat = "yyyy-MM-dd"

    var out = "# Catalogue\n\n"
    out += "\(items.count) file\(items.count == 1 ? "" : "s"), exported \(stamp.string(from: date))\n\n"
    guard !items.isEmpty else { return out }

    out += "| Name | Author | Year | Pages | Size | Folder |\n"
    out += "|---|---|---|---|---|---|\n"
    for item in items {
        let guess = known[item.key]
        let entry = bibEntries(for: [item], known: known).first
        let size = item.byteCount.map {
            ByteCountFormatter.string(fromByteCount: Int64($0), countStyle: .file)
        } ?? ""
        let folder = (item.relativePath as NSString).deletingLastPathComponent
        let cells = [
            markdownEscape(item.destinationName, inTable: true),
            markdownEscape(guess?.author ?? "", inTable: true),
            markdownEscape(entry?.year ?? "", inTable: true),
            item.pageCount.map(String.init) ?? "",
            size,
            markdownEscape(folder, inTable: true),
        ]
        out += "| " + cells.joined(separator: " | ") + " |\n"
    }
    return out
}

/// The bibliography as prose rather than BibTeX, for a document rather than a reference
/// manager.
public func markdownBibliography(_ entries: [BibEntry], date: Date = Date()) -> String {
    var out = "# Bibliography\n\n"
    guard !entries.isEmpty else {
        out += "_Nothing to list._\n"
        return out
    }
    for entry in entries.sorted(by: { $0.key < $1.key }) {
        var line = "- "
        if let author = entry.author { line += "\(markdownEscape(author)). " }
        line += "**\(markdownEscape(entry.title))**"
        if let year = entry.year { line += " (\(year))" }
        out += line + "\n"
    }
    return out
}

// MARK: - Reading the marks in a document

struct PDFWord: Equatable {
    let text: String
    let bounds: CGRect
}

private final class PDFWordParser: NSObject, XMLParserDelegate {
    private let pageBounds: CGRect
    private(set) var words: [PDFWord] = []
    private var currentText = ""
    private var currentBounds: CGRect?

    init(pageBounds: CGRect) {
        self.pageBounds = pageBounds
    }

    func parser(_ parser: XMLParser, didStartElement elementName: String,
                namespaceURI: String?, qualifiedName qName: String?,
                attributes attributeDict: [String: String] = [:]) {
        guard elementName == "word",
              let xMin = Double(attributeDict["xMin"] ?? ""),
              let yMin = Double(attributeDict["yMin"] ?? ""),
              let xMax = Double(attributeDict["xMax"] ?? ""),
              let yMax = Double(attributeDict["yMax"] ?? ""),
              xMax >= xMin, yMax >= yMin else { return }
        currentText = ""
        currentBounds = CGRect(x: xMin + pageBounds.minX,
                               y: pageBounds.maxY - yMax,
                               width: xMax - xMin,
                               height: yMax - yMin)
    }

    func parser(_ parser: XMLParser, foundCharacters string: String) {
        guard currentBounds != nil else { return }
        currentText += string
    }

    func parser(_ parser: XMLParser, didEndElement elementName: String,
                namespaceURI: String?, qualifiedName qName: String?) {
        guard elementName == "word" else { return }
        let text = currentText.trimmingCharacters(in: .whitespacesAndNewlines)
        if let bounds = currentBounds, !text.isEmpty {
            words.append(PDFWord(text: text, bounds: bounds))
        }
        currentText = ""
        currentBounds = nil
    }
}

/// Parses Poppler's layout coordinates into the page coordinate system PDFKit uses.
/// Kept internal so the parser can be tested without requiring a particular PDF utility
/// to be installed on the test machine.
func pdfBBoxWords(_ data: Data, pageBounds: CGRect) -> [PDFWord]? {
    let parser = PDFWordParser(pageBounds: pageBounds)
    let xml = XMLParser(data: data)
    xml.delegate = parser
    guard xml.parse() else { return nil }
    return parser.words
}

private let pdfWordCache = NSCache<NSString, PDFWordPage>()

private final class PDFWordPage: NSObject {
    let words: [PDFWord]

    init(words: [PDFWord]) {
        self.words = words
    }
}

private func bboxWords(for page: PDFPage) -> [PDFWord]? {
    guard let document = page.document,
          let url = document.documentURL,
          document.index(for: page) >= 0,
          let tool = locate("pdftotext") else { return nil }
    let index = document.index(for: page)

    let values = try? url.resourceValues(forKeys: [.fileSizeKey, .contentModificationDateKey])
    let cacheKey = "\(url.path)#\(index)#\(values?.fileSize ?? 0)#\(values?.contentModificationDate?.timeIntervalSince1970 ?? 0)" as NSString
    if let cached = pdfWordCache.object(forKey: cacheKey) { return cached.words }

    let process = Process()
    process.executableURL = tool
    let pageNumber = index + 1
    process.arguments = ["-bbox", "-f", "\(pageNumber)", "-l", "\(pageNumber)", url.path, "-"]
    let output = Pipe()
    process.standardOutput = output
    process.standardError = FileHandle.nullDevice
    do { try process.run() } catch { return nil }
    let data = output.fileHandleForReading.readDataToEndOfFile()
    process.waitUntilExit()
    guard process.terminationStatus == 0,
          let words = pdfBBoxWords(data, pageBounds: page.bounds(for: .mediaBox)) else { return nil }
    pdfWordCache.setObject(PDFWordPage(words: words), forKey: cacheKey)
    return words
}

func bboxQuote(words: [PDFWord], in boxes: [CGRect]) -> String? {
    let selected = words.filter { word in
        boxes.contains { $0.insetBy(dx: -0.5, dy: -0.5).intersects(word.bounds) }
    }
    guard !selected.isEmpty else { return nil }

    let ordered = selected.sorted {
        let yDifference = abs($0.bounds.midY - $1.bounds.midY)
        if yDifference > 2 { return $0.bounds.midY > $1.bounds.midY }
        return $0.bounds.minX < $1.bounds.minX
    }
    var result = ""
    var previous: PDFWord?
    for word in ordered {
        if result.isEmpty {
            result = word.text
        } else if let previous,
                  previous.text.hasSuffix("-"),
                  previous.bounds.midY - word.bounds.midY > 2 {
            result += word.text
        } else {
            result += " " + word.text
        }
        previous = word
    }
    return result
}

/// A highlight or note already in a PDF, read from the file rather than from the app's
/// own state, so a separate process (the MCP server) can see what the reader marked.
public struct PDFMark: Sendable, Equatable {
    public var page: Int
    public var kind: String
    public var quoted: String
    public var note: String
    public var colour: String

    public init(page: Int, kind: String, quoted: String, note: String, colour: String = "") {
        self.page = page
        self.kind = kind
        self.quoted = quoted
        self.note = note
        self.colour = colour
    }
}

/// The text a mark covers.
///
/// Read per quadrilateral where there are quads: a mark spanning two lines has a bounding
/// box that also covers the end of the line between them, so the box alone picks up words
/// that were never highlighted.
public func quotedText(of annotation: PDFAnnotation, on page: PDFPage) -> String {
    let quads = annotation.quadrilateralPoints ?? []
    var boxes: [CGRect] = []
    if quads.count >= 4 {
        for start in stride(from: 0, to: quads.count - 3, by: 4) {
            let points = (0..<4).map { quads[start + $0].pointValue }
            let xs = points.map(\.x), ys = points.map(\.y)
            // PaperShelf writes local points, while imported PDFs commonly store the
            // same points in page space. Adding the origin to both forms shifts imported
            // marks away from their text, which is what made the Notes rail lose words.
            let isPageSpace = points.allSatisfy {
                $0.x >= annotation.bounds.minX && $0.x <= annotation.bounds.maxX
                    && $0.y >= annotation.bounds.minY && $0.y <= annotation.bounds.maxY
            }
            let origin = isPageSpace
                ? CGPoint.zero : annotation.bounds.origin
            boxes.append(CGRect(x: xs.min()! + origin.x,
                                y: ys.min()! + origin.y,
                                width: xs.max()! - xs.min()!,
                                height: ys.max()! - ys.min()!))
        }
    } else {
        boxes = [annotation.bounds]
    }
    if let words = bboxWords(for: page),
       let quote = bboxQuote(words: words, in: boxes),
       !quote.isEmpty {
        return quote
    }
    let pieces = boxes.compactMap { page.selection(for: $0)?.string }
    return pieces.joined(separator: " ")
        .split(whereSeparator: \.isWhitespace).joined(separator: " ")
}

/// Every highlight, underline, strikeout and note in a document, in reading order.
public func pdfMarks(in url: URL, passwords: [String] = []) -> [PDFMark] {
    guard let document = PDFDocument(url: url) else { return [] }
    if document.isLocked {
        for password in passwords where document.unlock(withPassword: password) { break }
    }
    let wanted: Set<String> = [PDFAnnotationSubtype.highlight.rawValue,
                               PDFAnnotationSubtype.underline.rawValue,
                               PDFAnnotationSubtype.strikeOut.rawValue,
                               PDFAnnotationSubtype.text.rawValue]

    var found: [PDFMark] = []
    for index in 0..<document.pageCount {
        guard let page = document.page(at: index) else { continue }
        for annotation in page.annotations {
            guard let type = annotation.type, wanted.contains("/" + type) || wanted.contains(type)
            else { continue }
            let quoted = annotation.type == "Text" ? "" : quotedText(of: annotation, on: page)
            let note = annotation.contents ?? ""
            guard !quoted.isEmpty || !note.isEmpty else { continue }
            // Pages are 1-based everywhere this app shows one.
            found.append(PDFMark(page: index + 1, kind: type.lowercased(),
                                 quoted: quoted, note: note,
                                 colour: annotationColour(annotation.color)))
        }
    }
    return found
}

private func annotationColour(_ colour: NSColor?) -> String {
    guard let rgb = colour?.usingColorSpace(.sRGB) else { return "" }
    let channels = [rgb.redComponent, rgb.greenComponent, rgb.blueComponent]
        .map { Int((max(0, min(1, $0)) * 255).rounded()) }
    return String(format: "#%02X%02X%02X", channels[0], channels[1], channels[2])
}
